### ISSUE TITLE
Are you still using this? Do you have demo site or usage doc?

### ISSUE THREAD

**Issue by linonetwo** [btheado/jsoneditor#2]
If I can use this, I won't need to write my https://github.com/tiddly-gittly/tiddlywiki-plugins/blob/a70a9b3eb1f98980fc2b2801cf7a0a44dbeacce8/src/smart-field/src/readme.tid

**Comment by btheado** [comment]
No, I never really made use of it. There is an online demo at https://btheado.github.io/jsoneditor.html. @joshuafontany has a fork at https://github.com/joshuafontany/TW5-jsoneditor. I'm not sure what additions/changes he made.

**Comment by linonetwo** [comment]
Okay, I think this can make something like Tana's supertag [https://help.tana.inc/getting-started-and-overview/introduction-to-supertags.html](https://help.tana.inc/getting-started-and-overview/introduction-to-supertags.html) , and can be useful in todo management
